### ISSUE TITLE
Django Dashboard Material - Can't register a new user with docker 

### ISSUE THREAD

**Issue by Algogator** [app-generator/django-dashboard-material#3] opened 2020-03-11 15:04 UTC
Request Method: | POST
http://localhost:5005/register/
3.0.4
TypeError
'sslmode' is an invalid keyword argument for this function
/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py in get_new_connection, line 199
/usr/local/bin/python
3.6.10
['/',  '/usr/local/bin',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages']
Wed, 11 Mar 2020 15:04:05 +0000

Trace:

http://dpaste.com/00VSJQT

**Comment by app-generator** [comment] 2020-03-11 16:10
Thanks - We are working on it.

**Comment by app-generator** [comment] 2020-03-11 17:56
This issue is caused by [Heroku](https://www.heroku.com/) helpers, called in the [core.settings](https://github.com/app-generator/django-dashboard-material/blob/master/core/settings.py) file.

The patch:
```python
# contents of core/settings.py

# Activate Django-Heroku.
#django_heroku.settings(locals())
``` 
Note that this change will make the Heroku deployment unusable. 
I will close the issue.

**Comment by app-generator** [comment] 2020-03-11 17:57
@Algogator let us know if this patch works for you. 
Thanks for using our products.

**Closed by app-generator** 2020-03-11 17:57 UTC
